# docker-compose.yml

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
        - ./frontend:/app
        - /app/node_modules
    command: npm run dev

  backend:
    build: ./backend
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: userpassword
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    user: "rails"
    depends_on:
      - db
    restart: always

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
    restart: always

volumes:
  db_data: